// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by tarsier_env script.
import 'package:flutter/services.dart' show rootBundle;
import 'package:tarsier_env/tarsier_env.dart';

/// A class to access environment variables.
///
/// Environment variables are stored in a static map and can be accessed using getters.
class Env {
  static Map<String, String> _variables = {};

  // This function must be called in the main function to
  // initialize first all environment variables
  static init() async {
    final content = await rootBundle.loadString('.env');
    _variables = parseEnv(content);
  }

  /// Function to get value dynamically
  static T get<T>(String key, [T? defaultValue]) {
    final value = _variables[key];
    if (value == null) return resolvedDefaultValue<T>(defaultValue);
    return convertType<T>(value) ?? resolvedDefaultValue<T>(defaultValue);
  }

  static Map<String, String> get vars => _variables;
  static String? get appName => _variables['APP_NAME'];
  static String? get appEnv => _variables['APP_ENV'];
  static String? get appKey => _variables['APP_KEY'];
  static String? get appDebug => _variables['APP_DEBUG'];
  static String? get appUrl => _variables['APP_URL'];
  static String? get redisHost => _variables['REDIS_HOST'];
  static String? get redisPassword => _variables['REDIS_PASSWORD'];
  static String? get redisPort => _variables['REDIS_PORT'];
  static String? get mailDriver => _variables['MAIL_DRIVER'];
  static String? get mailHost => _variables['MAIL_HOST'];
  static String? get mailPort => _variables['MAIL_PORT'];
  static String? get mailUsername => _variables['MAIL_USERNAME'];
  static String? get mailPassword => _variables['MAIL_PASSWORD'];
  static String? get mailEncryption => _variables['MAIL_ENCRYPTION'];
  static String? get awsAccessKeyId => _variables['AWS_ACCESS_KEY_ID'];
  static String? get awsSecretAccessKey => _variables['AWS_SECRET_ACCESS_KEY'];
  static String? get awsDefaultRegion => _variables['AWS_DEFAULT_REGION'];
  static String? get awsBucket => _variables['AWS_BUCKET'];
  static String? get pusherAppId => _variables['PUSHER_APP_ID'];
  static String? get pusherAppKey => _variables['PUSHER_APP_KEY'];
  static String? get pusherAppSecret => _variables['PUSHER_APP_SECRET'];
  static String? get pusherAppCluster => _variables['PUSHER_APP_CLUSTER'];
}
